services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # SSL 인증서 경로
    networks:
      - benepick-app-network

networks:
  benepick-app-network:
    external: true
